// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PurchasemanagmnetSystem.Models;

namespace PurchasemanagmnetSystem.Migrations
{
    [DbContext(typeof(ConnectionStringClass))]
    partial class ConnectionStringClassModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("PurchasemanagmnetSystem.Models.Employee", b =>
                {
                    b.Property<int>("emp_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("emp_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("emp_id");

                    b.ToTable("employees");
                });

            modelBuilder.Entity("PurchasemanagmnetSystem.Models.Inssurance", b =>
                {
                    b.Property<int>("insurrance_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("emp_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("iss_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("qnty")
                        .HasColumnType("int");

                    b.HasKey("insurrance_id");

                    b.ToTable("inssurances");
                });

            modelBuilder.Entity("PurchasemanagmnetSystem.Models.Item", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("item_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("items");
                });

            modelBuilder.Entity("PurchasemanagmnetSystem.Models.Purchase", b =>
                {
                    b.Property<int>("product_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<double>("product_price")
                        .HasColumnType("float");

                    b.Property<int>("product_qty")
                        .HasColumnType("int");

                    b.Property<DateTime>("pur_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("purchase_item")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vendor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("product_id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("PurchasemanagmnetSystem.Models.Vendor", b =>
                {
                    b.Property<int>("vendor_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("item_status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vendor_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("vendor_id");

                    b.ToTable("vendors");
                });
#pragma warning restore 612, 618
        }
    }
}
